### PR TITLE
Create scikit learn tutorial_PT-BR.Rmd

### PR DESCRIPTION
**Pull request by Sandokhan**
First commit in the process of transalation of this material to brazilian portuguese.

### CODE REVIEW

**Comment by Sandokhan** [comment]
The process of translation are

**Comment by Sandokhan** [comment]
The scikit learn tutorial are translated to brazilian portuguese

**Review by Kacawi-zz — APPROVED** [review]
Looks very good to me - Thanks for your contribution, Sandokhan!!

**Comment by Sandokhan** [comment]
That is my pleasure, Kacawi!!

**Pull request merged**
